name: PR Build

on:
  pull_request:
    branches:
      - develop

jobs:

  andoid-lint-check:
    name: Run android lint check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with: { java-version: 1.8 }
      - name: Run Android Lint
        run: ./gradlew lint

  detekt-check:
    name: Run detekt check
    runs-on: ubuntu-latest

    steps:
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with: { java-version: 1.8 }
      - name: Run detekt
        run: ./gradlew detekt

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 1.8 }
      - name: Run unit tests
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
